### ISSUE TITLE
部署遇到 ERROR: Head "https://ghcr.io/v2/kunzfw/kindleear/manifests/latest": denied 错误

### ISSUE THREAD

**Issue by 6uu1** [KUNzfw/KindleEar-Docker#6]

**Comment by coekfung** [comment]
请使用https://ghcr.io/v2/wzf03/kindleear/manifests/latest

**Comment by coekfung** [comment]
> 请使用https://ghcr.io/v2/wzf03/kindleear/manifests/latest

即 ghcr.io/wzf03/kindleear:latest
