### ISSUE TITLE
KindleEar大更新了，这个会更新吗？

### ISSUE THREAD

**Issue by Jun3101** [KUNzfw/KindleEar-Docker#8]
KindleEar大更新了，这个会更新吗？

**Comment by coekfung** [comment]
感谢你的提醒！我大概看了一下，原项目摆脱了对GAE的依赖，相信处理起来会方便很多。

**Comment by coekfung** [comment]
但是我看了一下，原项目已经提供了dockerfile，那么这个项目也没有存在的必要了
